name: Compara Templates

on:
  workflow_call:
    inputs:
      ref: 
        required: true
        description: 'Ref do branch a ser comparado'
        type: string
        default: main
    # secrets:
    #   token: 
    #     required: true


jobs:
  compara_diretorios:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repositório atual
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        token: ${{ secrets.WORKFLOW_TOKEN }}

    - name: Checkout repositório remoto
      uses: actions/checkout@v4
      with:
        repository: robthross/static_website
        path: remote_repo
        ref: main

    - name: Configura Ambiente Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install dependencies
      run: pip install ruamel.yaml

    - name: Rodando Script de Comparação e Sincronia
      run: |
        python .github/scripts/compare_yaml.py

    - name: Configura workflow
      run: |
        python .github/scripts/set_up_workflow.py


    - name: Faz o push caso apresente falha
      run: |
        rm -rf remote_repo/
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .github/
        if [[ $(git status --porcelain) ]]; then
          git commit -m "Sync .github com o diretório remoto [skip ci]"
          git push
        else
          echo "Sem mudanças para comitar"
        fi
    continue-on-error: true
