name: Compare .github directories

on: [push, pull_request]

jobs:
  compare_directories:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repositório
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.WORKFLOW_TOKEN }}

    - name: Checkout repositório remoto
      uses: actions/checkout@v4
      with:
        ref: main
        repository: robthross/static_website
        path: remote_repo

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Rodando Script de Comparação e Sincronia
      run: |
        python .github/scripts/compare_and_sync.py

    - name: Faz o push caso apresente falha
      if: ${{ failure() }}
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .github/
        git commit -m "Sync .github com o diretório remoto"
        git push


    # - name: Setup Python
    #   uses: actions/setup-python@v4
    #   with:
    #     python-version: '3.x'

    # - name: Install dependencies
    #   run: pip install ruamel.yaml

    # - name: Compare and sync YAML files
    #   run: python .github/scripts/compare_and_sync.py

