name: Compare .github directories

on: [push, pull_request]

jobs:
  compara_template:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Checkout remote repository
      uses: actions/checkout@v3
      with:
        repository: robthross/static_website
        path: static_website

    - name: Compare .github directories
      id: compare_dirs
      run: |
        diff_result=$(diff -qr .github/ static_website/.github/)
        if [ "$diff_result" ]; then
          echo "::error::Existe diferenças entre as diretórios .github:"
          echo "$diff_result"
          exit 1
        else
          echo "Não existem diferenças entre as diretórios .github do repositório local e remoto."
        fi
