name: Compara Templates

on: [push, pull_request]

jobs:
  compara_diretorios:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repositório atual
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
        token: ${{ secrets.WORKFLOW_TOKEN }}

    - name: Checkout repositório remoto
      uses: actions/checkout@v4
      with:
        repository: robthross/static_website
        path: remote_repo
        ref: main

    - name: Configura Ambiente Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Rodando Script de Comparação e Sincronia
      run: |
        python .github/scripts/compare_and_sync.py

    - name: Configura workflow
      if: ${{ failure() }}
      run: |
        python .github/scripts/set_up_workflow.py

    - name: Faz o push caso apresente falha
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .github/
        git commit -m "Sync .github com o diretório remoto"
        git push

    - name: Install dependencies
      run: pip install ruamel.yaml

    - name: Configura workflow
      run: python .github/scripts/set_up_workflow.py

