name: Compare and Sync .github directories

on: [push, pull_request]

jobs:
  compare_and_sync_directories:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Checkout remote repository
      uses: actions/checkout@v4
      with:
        repository: robthross/static_website # Substitua 'owner/repo' pelo repositório remoto
        path: static_website

    - name: Compare os arquivos local com o Template
      id: compare_dirs
      run: |
        DIFF=$(diff -qr --exclude=check-template.yml .github/ static_website/.github/)
        if [ "$DIFF" ]; then
            echo "::error::Diferenças encontradas no diretório .github:"
            echo "$DIFF"
            echo "::error::Sincronizar os arquivos diferentes do remoto para o local."
            # Sincronizar os arquivos diferentes do remoto para o local
            rsync -av --exclude=check-template.yml static_website/.github/ .github/
            ls -lha
            exit 0
        else
            echo "Não existem diferenças entre as diretórios e arquivos."
        fi

    - name: Push os arquivos se não foram sincronizados
      if: ${{ failure() }}
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git status
        git add .
        git commit -m "Sync o diretorio .github com o Template"
        git push
