name: Compare and Sync .github directories

on: [push, pull_request]

jobs:
  compare_and_sync_directories:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Checkout remote repository
      uses: actions/checkout@v4
      with:
        repository: robthross/static_website # Substitua 'owner/repo' pelo repositório remoto
        path: remote_repo

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run Python comparison and sync script
      run: |
        python .github/scripts/compare_and_sync_github_dirs.py

    - name: Push changes if any files were synced
      if: ${{ failure() }}
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .github/
        git commit -m "Sync .github directory with remote repository"
        git push
