on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - bucket_name: 'portal'
      - bucket-key: 'global'      - bucket-key: 'global'      - bucket_name: 'vai'
